### PR TITLE
Add fix for issue #352 of sql server adapter and composite-primary-keys/composite_primary_keys#224

### PR DESCRIPTION
**Pull request by jmozmoz**
https://github.com/composite-primary-keys/composite_primary_keys/issues/224

### CODE REVIEW

**Comment by gbenedict** [comment]
+1 for merging this.

**Comment by metaskills** [comment]
I will be working on old issues and pull requests after I get the 4.2 work done in master.

**Comment by spcurry** [comment]
Another +1 for merging this PR :)

**Comment by metaskills** [comment]
There has been major changes in the 4.2 adapter and this PR may not work anymore. Please test the latest version out update if needed. http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

Otherwise, I will get back to her in a few days or so.

**Comment by jmozmoz** [comment]
At the moment I have only access to SQL Server 9 so I cannot test the new version. Nevertheless, I think this pull request should be merged into the 4.1 branch.

**Comment by metaskills** [comment]
Closing this issue, I made a comment on the linked ticket. That project should freedom patch `sql_for_insert` just like they did for PostgreSQL.

**Pull request closed without merging**
