### PR TITLE
Rails 6

### PR DESCRIPTION
**Pull request by wpolicarpo**
This is a WIP pull request to bring Rails 6 changes to SQL Server adapter.

O lot of people asked how they can help and what are the failing tests we should fix to have a stable version. Best thing to do is to check the latest Travis build for this branch, see what is failing and then open a PR for this branch.

### CODE REVIEW

**Comment by daveomcd** [comment]
I was going to attempt at helping with pushing this along, however I do not have experience working on a ruby/rails gem. Nevertheless, why let that deter me.  I forked and git cloned the [6-0-dev](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/6-0-dev) branch to my local machine and then ran RAKE to see if it would pass the tests before I began breaking things.

That's when I received the following... 

`daveomcd@mcdonald-precis:~/open_source/activerecord-sqlserver-adapter$ rake
rake aborted!
NoMethodError: undefined method `full_gem_path' for nil:NilClass
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/test/support/paths_sqlserver.rb:15:in `root_activerecord'
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/test/support/paths_sqlserver.rb:19:in `root_activerecord_lib'
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/test/support/paths_sqlserver.rb:27:in `test_load_paths'
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/test/support/paths_sqlserver.rb:31:in `add_to_load_paths!'
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/test/support/paths_sqlserver.rb:49:in `<top (required)>'
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/rakefile:3:in `require_relative'
/mnt/c/Users/mcdonaldd/Documents/open_source/activerecord-sqlserver-adapter/rakefile:3:in `<top (required)>'
/home/daveomcd/.rvm/gems/ruby-2.6.1/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/daveomcd/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
/home/daveomcd/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)`

Am I doing something incorrect? Or is there a guide for some setup when cloning a gem that I could read up on somewhere to get me started?  My apologies if this isn't the place to post this.

**Comment by robikovacs** [comment]
Hey @wpolicarpo 

Do you need help with this PR? Let me know how I can help.

Cheers,
Robi

**Comment by wpolicarpo** [comment]
@robikovacs any help is welcome here, yes. We have @aidanharan currently working on having all the tests passing and some other initiatives already started as PRs.

Maybe we can build a list of failing tests and tackle them one by one (or by groups if it's more relevant).

**Comment by rjerickson** [comment]
Thank you very much, wpolicarpo, for all of your work on this!

**Comment by peliav** [comment]
Hi @wpolicarpo. Have you compiled the list of failing tests yet? Maybe I can help too.

**Comment by aidanharan** [comment]
There is no compiled list of failing tests but you can see them if you click on the red X next to the latest commit on the `6-0-dev` branch (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commits/6-0-dev). If you open the Travis link and then one of the builds you will see something like https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/670183329?utm_medium=notification&utm_source=github_status

Currently there are "53 failures, 34 errors" tests that need to be fixed. This is a table with some of the most common problems and the number of tests affected. Its not a complete list.

| First Header  | Second Header | Notes
| ------------- | ------------- | ---
| The ORDER BY clause is invalid in views...  															| 14 | @aidanharan investigating |
| [X] instead of [Y] queries were executed. 															| 15 |  |
| ActiveRecord::ReadOnlyError expected but nothing was raised  											| 8  |  |
| ActiveRecord::UnknownAttributeReference: Query method called with non-attribute argument 				| 2  |  |
| Cannot truncate table 'author_addresses' because it is being referenced by a FOREIGN KEY constraint 	| 5  | PR https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/755 opened |
| wrong number of arguments 																			| 2  |  |
| NoMethodError: undefined method `table_name' 															| 2  |  |
| Expected a deprecation warning 																		| 9  |  |

@peliav Great if you have a look into one of these are any other of the failing tests.

**Comment by YehudaGold** [comment]
## summary of the current failed tests as i see it:

In PR:
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/780
   - **fix test from files:** dirty_test, transactions_test, persistence_test , adapter_test, belongs_to_associations_test, has_one_associations_test.
  -  **need fix:**  BasicsTest#test_0023_an empty transaction does not raise if preventing writes
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/785
  -  DefaultNumbersTest#test_default_decimal_number
---

Changes that in PR in Active record (needs a temporary fixes):
-  https://github.com/rails/rails/pull/37170
   -  query_cache_test#test_insert_all
- https://github.com/rails/rails/pull/38037 
  -  FilterAttributesTest#test_0008_filter_attributes on pretty_print
FilterAttributesTest#test_0010_filter_attributes on pretty_print should handle [FILTERED] value properly
   **only on ruby > 2.7**
---

current failed tests:
- AdapterForeignKeyTest#test_foreign_key_violations_on_delete_are_translated_to_specific_exception
  - InvalidForeignKey exception not  match the regex in `translate_exception`  
 
- log_subscriber_test#test_vebose_query_logs

- EagerLoadingTooManyIdsTest#test_preloading_too_many_ids:37 
  - related to: https://github.com/rails/rails/issues/34945

- CacheKeyTest#test_0005_cache_version is the same when it comes from the DB or from the user 
CacheKeyTest#test_0008_cache_version does NOT call updated_at when value is from the database 
CacheKeyTest#test_0006_cache_version does not truncate zeros when timestamp ends in zeros
  - related to the new ActiveRecord::Relation#cache_version feature

 - TimePrecisionTest#test_no_time_precision_isnt_truncated_on_assignment

- RelationTest#test_reorder_with_take
 RelationTest#test_reorder_with_first
  -  related to: https://github.com/rails/rails/pull/36889



Hope this helps  to make sense from the tests :)

**Pull request merged**
