### PR TITLE
fix: enhance user_options' parsing (#535)

### PR DESCRIPTION
**Pull request by arbesulo**
In some cases the values are returned as an array, and not as a hash.

### CODE REVIEW

**Comment by metaskills** [comment]
> I can help with the tests. I noticed this patch for user options first landed in 4-0-stable. I think we should patch it for 2-3-stable up to 3-2-stable.

Address #535 and I'll prioritize this after the Rails v5 work.

**Comment by teaearlgraycold** [comment]
Applying this patch to master allows this to work for me in Rails 5, thanks

**Comment by kride** [comment]
Same issue when upgrading from 4.2.3 to 5.0.1. This patch would fix it.

**Comment by metaskills** [comment]
FYI, I'll have this work done this week in various branches.

**Comment by metaskills** [comment]
Just pushed v3.2.16, v4.2.17, and v5.0.3 with this change.

**Pull request merged**
