### PR TITLE
6 0 dev

### PR DESCRIPTION
**Pull request by nemesit**

### CODE REVIEW

**Comment by nemesit** [comment]
down to 45 errors 55 fails in active record tests and 0 fails 0 errors in sqladapter

**Comment by dglaser** [comment]
May want to **NOT** include the [testing - b4f558e](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/731/commits/b4f558e6927a05d46fe92e00e7ae2bd9d250f2b9) commit. It assigns `@sqlserver_options` to an empty hash, likely causing other issues. @ttilberg discussed this [HERE](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/714#issuecomment-587600292)

He provided a patch to my PR that changed the altered code back.

**Comment by ttilberg** [comment]
@dglaser I was just reviewing these changes, and  it looks like a future commit does indeed fix that issue. At the end of this changeset, it includes assignment with `**sqlserver_options`.

This looks like great progress!

**Comment by dglaser** [comment]
- The Gemfile needs to be reverted back to remove hard coded rails and tiny_tds gems.
- The VERSION file represents what version we have the adapter at. Can use  `export RAILS_VERSION='6.0.2.1'` to choose the rails version.
- I'm not sure about changing the Docker image in Dockerfile. Would like to have a standard image that is kept updated with this project.

**Comment by dglaser** [comment]
- The Gemfile needs to be reverted back to remove hard coded rails and tiny_tds gems.
- The VERSION file represents what version we have the adapter at. Can use export RAILS_VERSION='6.0.2.1' to choose the rails version.
- I'm not sure about changing the Docker image in Dockerfile. Think its best to stay with a standard image that is kept updated with this project, as @wpolicarpo has done so far.

**Comment by nemesit** [comment]
could do yeah, though official tinytds also needs to be updated a bit for ruby 2.7, and it results in one less error too. The rest sure, just wanted up to date images to test

**Comment by dglaser** [comment]
I was only throwing in my 2 cents. As a user, I appreciate wanting an up-to-date image. Maybe the source could be a git repo here for us to submit PR's to and the "owners" to deploy to rails-sqlserver hub??

**Comment by aidanharan** [comment]
The tests on `master` are now passing and the changes have been pulled into the `6-0-dev` branch. 

We should get the adapter working against Rails 6.0.0 before moving onto higher releases so that older releases can be supported.

@nemesit: Would you be able to merge the latest changes into your `nemesit:6-0-dev` branch?

**Comment by nemesit** [comment]
done

**Comment by wpolicarpo** [comment]
@nemesit do you mind rebasing your branch? I have pushed new Docker images for all newer rubies now and moved them to a new `railssqlserver` org (they were under my username before).

**Comment by wpolicarpo** [comment]
Closing this in favor of #690.

**Pull request closed without merging**
