### PR TITLE
Overwrite _type_cast method

### PR DESCRIPTION
**Pull request by merodriguezblanco**
Follows discussion at #491

### CODE REVIEW

**Comment by metaskills** [comment]
Awesome. I'll get to this soon. Head down in v5 work.

**Comment by merodriguezblanco** [comment]
Hi @metaskills , how's it going?

I know you are very busy with v5, and I'm looking forward to it :)  Still, I wanted to know if you had the chance to check this code?

Thanks!

**Comment by metaskills** [comment]
Noted :)

**Comment by zacharywelch** [comment]
+1 😸

**Comment by michael-garland** [comment]
👍

**Comment by meadoch1** [comment]
@metaskills Any idea when this fix would make it into an official release?  We're hitting it too using the latest release of the gem.

**Comment by metaskills** [comment]
I have to prioritize the Rails v5 release. Been hard at work over the past month on it. I suspect it'll be done very soon, but may need a few days break, so honestly this could be a week or more easily.

**Comment by meadoch1** [comment]
That's reasonable.  Thanks!

**Comment by metaskills** [comment]
Thanks, please try v4.2.16 with this change.

**Pull request merged**
