### PR TITLE
Dump column collation to schema.rb and allow collation changes using column_change

### PR DESCRIPTION
**Pull request by mgrunberg**
This PR address https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/848. 

It also adds support to change collation `change_column :customers, :name, collation: :xxx`. Before this change, collation changes were skipped/ignored.

### CODE REVIEW

**Comment by mgrunberg** [comment]
I decided to implement this on 6-0-stable since it's a small change. If it wasn't the right call and it should be targeting main, let me know.

**Comment by mgrunberg** [comment]
I've just realized that the issue was reported for 5-2-stable. 

The fix is almost the same. The only difference with this PR is that the change in `lib/active_record/connection_adapters/sqlserver/schema_statements.rb` should be
```
sql_commands.last << " COLLATE #{options[:collation]}" if options[:collation].present?
```
and not
```
alter_command += " COLLATE #{options[:collation]}" if options[:collation].present?
```

I'm not sure what's the best here. I can make another PR for 5-2-stable.

**Comment by wpolicarpo** [comment]
PRs should target the `main` branch. We can backport to stable branches if necessary. Can you rebase your branch and change the target to `main`?

**Comment by mgrunberg** [comment]
@wpolicarpo, no problem. I've rebase with main and change target to main.

**Comment by wpolicarpo** [comment]
LGTM. Can you resolve the changelog conflict?

**Comment by mgrunberg** [comment]
@wpolicarpo, conflicts fixed

**Pull request merged**
