### PR TITLE
Rails 6.1 support and bit type bug fix

### PR DESCRIPTION
**Pull request by Circuit8**
This expands on #853 by fixing the test suite.

We also discovered that if a column is a "bit" type, and it has a default value of `true`, we would get an error from active record, as it seems that in the current version it is expecting boolean columns to be cast to `"1"` for true values, rather than `true`. This PR fixes that aswell.

### CODE REVIEW

**Comment by marciojg** [comment]
@wpolicarpo Can you help us doing a merge of this PR and create a new release?

**Comment by wpolicarpo** [comment]
@Circuit8 can you please rebase your branch against `main`?

**Comment by Circuit8** [comment]
@wpolicarpo sure thing, should be sorted now.

**Comment by runephilosof-abtion** [comment]
@Circuit8 You did not rebase this branch onto main. You merged main into this branch.

From https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/861#discussion_r613280110
> Not sure if that was the best approach to solve that issue. The fact that you had to change a spec rings a bell that something might be wrong there.
>
> TinyTDS casts the bit data type to boolean, can't see why we should change it at the adapter level. That could lead to unexpected bugs/changes to already existing apps assuming boolean as true/false instead of 1/0.
>
> In any case #875 addressed the original issue already.

**Comment by wpolicarpo** [comment]
The remaining changes in this PR were superseded by #875 so I'm closing this off.

**Pull request closed without merging**
