### PR TITLE
added support for MSSQL2016

### PR DESCRIPTION
**Pull request by udaykadaboina**
Added Support for MSSQL2016

### CODE REVIEW

**Comment by udaykadaboina** [comment]
@metaskills can you take a look and let me know if I need to do anything more?

**Comment by metaskills** [comment]
Thanks. What branch are you making this pull request too? We dropped that version stuff in 4-2-stable and forward so this could only be relevant for 4-1-stable and below.

**Comment by udaykadaboina** [comment]
@metaskills I'm looking for 3-2-stable. Thanks!

**Comment by metaskills** [comment]
Perfect, I see now too!

screen shot 2016-10-06 at 7 47 33 am

**Comment by udaykadaboina** [comment]
@metaskills Strangely for some reason this branch is missing a method:

```
      def sqlserver_2014?
        @database_year == 2014
      end
```

If you would like, I can add this too and then it will be ready to package into a new gem version? Let  me know!

**Comment by metaskills** [comment]
I can do that, because when I add this, I will have to cut a new branch for 3.2, 4.0, and 4.1

**Comment by udaykadaboina** [comment]
@metaskills Awesome! 👍  will keep an eye for the new version of gem.

**Comment by udaykadaboina** [comment]
@metaskills @annaswims Hi! Is there an eta of when new version will be released? 

Thanks!

**Comment by metaskills** [comment]
No, but I am making good progress for Hacktoberfest this month on it :)

**Comment by metaskills** [comment]
Thanks, but I just went ahead and pushed updates to 3-2-stable up to 4-1-stable that allows vNext. New gems pushed to rubygems.org too. Cheers!!!

**Pull request closed without merging**
